name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FORCE_COLOR: '3' # asks Chalk to use colors in logs of Yarn, Jest, ESLint and many others

jobs:
  code-checks:
    name: Code checks
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: browniebroke/read-nvmrc-action@v1 # Read node version from `.nvmrc` file
        id: nvmrc
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: '${{ steps.nvmrc.outputs.node_version }}'
          cache: 'npm'
      - name: npm install
        env:
          CI: true
        run: npm install --prefer-offline --no-audit
      - name: npm run lint:typescript
        run: |
          npm run lint:typescript
          git status
          echo ℹ️  If this test fails, run `npm run lint:typescript` and commit the changes.
          exit $(git diff | wc -l)
      - name: npm run lint:fix
        run: |
          npm run lint:fix
          git status
          echo ℹ️  If this test fails, run `npm run lint:fix` and commit the changes.
          exit $(git diff | wc -l)
      - name: npm run lint:format
        run: |
          npm run lint:format
          git status
          echo ℹ️  If this test fails, run `npm run lint:format` and commit the changes.
          exit $(git diff | wc -l)

  approval-tests:
    name: Approval tests
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    services:
      mongodb:
        image: docker://mongo:3.4
        ports:
          - 27117:27017
    steps:
      - uses: actions/checkout@v2
      - uses: browniebroke/read-nvmrc-action@v1 # Read node version from `.nvmrc` file
        id: nvmrc
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: '${{ steps.nvmrc.outputs.node_version }}'
          cache: 'npm'
      - uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: env-vars-testing.conf
      - name: npm install
        env:
          CI: true
        run: npm install --prefer-offline --no-audit
      - name: Approval tests
        run: npm run test:approval
      # - name: Get coverage data
      #   run: |
      #     sleep 2 # give some time for nyc (npm run start:coverage) to save coverage info
      #     npx nyc report --reporter=lcov # stores the coverage report in coverage/lcov.info
      # - name: Save code coverage results
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: approval-code-coverage-report
      #     path: |
      #       .nyc_output
      #       coverage

  unit-tests:
    name: Unit tests
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: browniebroke/read-nvmrc-action@v1 # Read node version from `.nvmrc` file
        id: nvmrc
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: '${{ steps.nvmrc.outputs.node_version }}'
          cache: 'npm'
      - name: npm install
        env:
          CI: true
        run: npm install --prefer-offline --no-audit
      - name: Unit tests
        env:
          CI: true
        run: npm run test:unit

  integration-tests:
    name: Integration tests
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    services:
      mongodb:
        image: docker://mongo:3.4
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - uses: browniebroke/read-nvmrc-action@v1 # Read node version from `.nvmrc` file
        id: nvmrc
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: '${{ steps.nvmrc.outputs.node_version }}'
          cache: 'npm'
      - uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: env-vars-testing.conf
      - name: npm install
        env:
          CI: true
        run: npm install --prefer-offline --no-audit
      - name: Initialize database
        env:
          CI: true
        run: npm run test-reset
      - name: Start Openwhyd server
        run: |
          npm start --mongoDbDatabase openwhyd_test &
          ./scripts/wait-for-http-server.sh 8080 # give openwhyd's server some time to start
      - name: API tests
        env:
          CI: true
        run: npm run test:integration

  refactor-coverage:
    name: Send test coverage of the `post` API to Codacy
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    services:
      mongodb:
        image: docker://mongo:3.4
        ports:
          - 27117:27017
    steps:
      - uses: actions/checkout@v2
      - uses: browniebroke/read-nvmrc-action@v1 # Read node version from `.nvmrc` file
        id: nvmrc
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: '${{ steps.nvmrc.outputs.node_version }}'
          cache: 'npm'
      - uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: env-vars-testing.conf
      - name: npm install
        env:
          CI: true
        run: npm install --prefer-offline --no-audit
      - name: Initialize database
        env:
          CI: true
        run: npm run test-reset
      - name: Run tests on `post` API
        env:
          CI: true
        run: npm run test:post:coverage
      - uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_REPOSITORY_TOKEN_FOR_COVERAGE }}
          coverage-reports: coverage/lcov.info

  cypress-tests:
    name: Cypress E2E tests
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    services:
      mongodb:
        image: docker://mongo:3.4
        ports:
          - 27017:27017
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: '${{ steps.nvmrc.outputs.node_version }}'
          cache: 'npm'
      - uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: env-vars-testing.conf
      - name: npm install
        env:
          CI: true
        run: npm install --prefer-offline --no-audit
      - name: Run Cypress tests against Openwhyd server
        uses: cypress-io/github-action@v2.7.2
        with:
          start: npm run start:coverage --mongoDbDatabase openwhyd_test
          wait-on: 'http://localhost:8080'
          config-file: cypress.json
          browser: 'chromium' # to include browser console in cypress logs
        env:
          CI: true
      - name: Get coverage data
        run: |
          # npm run test:coverage
          npx nyc report --reporter=lcov # stores the coverage report in coverage/lcov.info
      - name: Save code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: cypress-code-coverage-report
          path: |
            .nyc_output
            coverage
      # NOTE: screenshots will be generated only if E2E test failed
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

  docker:
    # To publish the Docker image from here, see https://github.com/openwhyd/openwhyd/pull/308/commits/1eacaa98885789642ba0073c9bb4d822021f0d95#diff-12a86cef0c4707531fdbabac3e38cb2aR36
    name: Docker tests
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and start services
        run: docker-compose up --build --detach
      - name: Init database for tests
        run: |
          docker-compose exec -T web npm run test-reset
          docker-compose restart web
          docker-compose exec -T web sh -c './scripts/wait-for-http-server.sh 8080'
      - name: Run unit tests
        run: docker-compose exec -T web npm run test:unit
      - name: Run API tests
        run: docker-compose exec -T web npm run test:integration
      - name: Logs from docker-compose
        if: ${{ always() }} # this step is useful to troubleshoot the execution of openwhyd when tests fail
        run: docker-compose logs
